/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_narcano_jni_CaffParser */

#ifndef _Included_com_narcano_jni_CaffParser
#define _Included_com_narcano_jni_CaffParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_narcano_jni_CaffParser
 * Method:    CallParser
 * Signature: (Ljava/lang/String;)[Lcom/narcano/jni/CIFF;
 */
JNIEXPORT jobjectArray JNICALL Java_com_narcano_jni_CaffParser_CallParser
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
